# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 275e8c7e4c5ba13e03234d09d7823cf8cb07c86a6690d060281196039af21fc86002b8b70d0b79cf5d776b9f543b944b70cf764178fde09b5ab83167ba0d50ad

test:
  secret_key_base: fb737968aeb686b9a7996b46dcf5ce02543f088452bfe4c17eac95d52ffee6400ea7ea40c5f6fd43d1cf19c66a09a9c5492f047146b116992a410d418746dc2f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
